apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sample-app-secrets
spec:
  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: "gitops-eks-demo/dev/sample-app"
        property: db_password
    - secretKey: API_KEY
      remoteRef:
        key: "gitops-eks-demo/dev/sample-app"
        property: api_key
