# External Secrets Operator â€” pulls secrets from AWS SSM/Secrets Manager
# Zero secrets stored in Git
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: sample-app-secrets
spec:
  refreshInterval: 1h

  secretStoreRef:
    name: aws-secretsmanager
    kind: ClusterSecretStore

  target:
    name: sample-app-secrets
    creationPolicy: Owner
    template:
      type: Opaque

  data:
    - secretKey: DB_PASSWORD
      remoteRef:
        key: "gitops-eks-demo/ENVIRONMENT/sample-app"
        property: db_password
    - secretKey: API_KEY
      remoteRef:
        key: "gitops-eks-demo/ENVIRONMENT/sample-app"
        property: api_key
