apiVersion: v1
kind: Namespace
metadata:
  name: sample-app
  labels:
    # Pod Security Standards â€” enforced at namespace level
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/warn: restricted
    pod-security.kubernetes.io/audit: restricted
    # Used by NetworkPolicies
    app.kubernetes.io/part-of: sample-app
