apiVersion: v1
kind: ServiceAccount
metadata:
  name: sample-app
  labels:
    app.kubernetes.io/name: sample-app
  annotations:
    # IRSA â€” grant AWS permissions via IAM role (set in overlay)
    eks.amazonaws.com/role-arn: ""
automountServiceAccountToken: false
